"""empty message

Revision ID: 289411b2e831
Revises: c2286538cdef
Create Date: 2020-12-18 11:43:03.147357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289411b2e831'
down_revision = 'c2286538cdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
